-- PM Proposals table
-- Run this in your Supabase SQL Editor (second migration)

CREATE TABLE IF NOT EXISTS pm_proposals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pm_brief_id UUID NOT NULL REFERENCES pm_briefs(id) ON DELETE CASCADE,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,

  -- Directions generated by PMCORE
  direction_fix_first TEXT,    -- Direction A: fix critical issues first
  direction_quick_start TEXT,  -- Direction B: start now, fix in parallel

  -- User choice
  chosen_direction TEXT,       -- 'A', 'B', or custom
  user_input TEXT,             -- optional notes from user

  -- PM Action Plan (like strategy_plan in marketing)
  pm_plan TEXT,

  -- Pricing extracted from plan
  proposed_price DECIMAL(10,2),
  execution_budget_min INTEGER,
  execution_budget_max INTEGER,
  currency TEXT NOT NULL DEFAULT 'EUR',

  -- Client-facing proposal document
  proposal_content TEXT,

  -- Status
  status TEXT NOT NULL DEFAULT 'draft',  -- draft | sent | accepted | rejected
  sent_at TIMESTAMPTZ,
  accepted_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS pm_proposals_brief_id_idx ON pm_proposals(pm_brief_id);
CREATE INDEX IF NOT EXISTS pm_proposals_company_id_idx ON pm_proposals(company_id);
