'use client';

import { useState } from 'react';
import { AnalysisResult } from '@/lib/types';

interface ExportButtonProps {
  companyName: string;
  results: AnalysisResult;
}

export default function ExportButton({ companyName, results }: ExportButtonProps) {
  const [exported, setExported] = useState(false);

  const handleExport = () => {
    const date = new Date().toISOString().split('T')[0];
    const markdown = `# MKTAGENT Marketing Intelligence Report
**Company**: ${companyName}
**Generated**: ${date}

---

## 1. EXECUTIVE SUMMARY
${results.executiveSummary}

---

## 2. COMPANY ANALYSIS
${results.companyAnalysis}

---

## 3. USER RESEARCH
${results.userResearch}

---

## 4. COMPETITOR ANALYSIS
${results.competitorAnalysis}

---

## 5. MARKETING STRATEGY
${results.marketingStrategy}

---

## 6. BUDGET ALLOCATION
${results.budgetAllocation}

---
*Generated by MKTAGENT — AI-powered marketing intelligence*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mktagent-${companyName.toLowerCase().replace(/\s+/g, '-')}-${date}.md`;
    a.click();
    URL.revokeObjectURL(url);

    setExported(true);
    setTimeout(() => setExported(false), 2000);
  };

  return (
    <button
      onClick={handleExport}
      style={{
        width: '100%',
        padding: '10px 16px',
        background: exported ? 'var(--acid)' : 'transparent',
        color: exported ? 'var(--ink)' : 'var(--chrome-muted)',
        border: `1px solid ${exported ? 'var(--acid)' : 'var(--ink-border)'}`,
        borderRadius: '8px',
        cursor: 'pointer',
        fontFamily: 'var(--font-dm-mono), monospace',
        fontSize: '12px',
        letterSpacing: '0.05em',
        transition: 'all 0.2s ease',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
      }}
      onMouseEnter={e => {
        if (!exported) {
          (e.currentTarget as HTMLElement).style.borderColor = 'var(--acid)';
          (e.currentTarget as HTMLElement).style.color = 'var(--acid)';
        }
      }}
      onMouseLeave={e => {
        if (!exported) {
          (e.currentTarget as HTMLElement).style.borderColor = 'var(--ink-border)';
          (e.currentTarget as HTMLElement).style.color = 'var(--chrome-muted)';
        }
      }}
      aria-label="Export report as markdown"
    >
      <span>{exported ? '✓' : '↓'}</span>
      {exported ? 'EXPORTED!' : 'EXPORT REPORT'}
    </button>
  );
}
